CREATE DATABASE larrydavid;
\c larrydavid;

CREATE TABLE lddailies (id SERIAL PRIMARY KEY, quote VARCHAR(255), source VARCHAR(255));
INSERT INTO lddailies (quote, source) VALUES ("Anyone can be confident with a full head of hair. But a confident bald man - there''s your diamond in the rough.", "Larry David"
INSERT INTO lddailies (quote, source) VALUES ("I''m married. I can wear whatever I want.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I''m available for sex all the time, basically.....Just assume that I want it all the time. So whenever you want it, just tap me on the shoulder.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I don''t particularly like children, you know, that''s why I dont have any, but I love being called Daddy.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Jews buy, like, 85% of the sun block that''s sold in this country, don''t you think?", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("People love when you ask them about what they''re doing.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I like to sing. I like to whistle. I like to play the bongos on my leg. I like to imitate horses, but I don''t do it because there''s somebody sitting next to me!", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I''ll have a vanilla...one of those vanilla bullshit things. You know, whatever you want, some vanilla bullshit latte cappa thing. Whatever you got.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I tend to say stupid things to black people sometimes.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I don''t think white people should have anything.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("A date is an experience you have with another person that makes you appreciate being alone.","Larry David");
INSERT INTO lddailies (quote, source) VALUES ("You know who wears sunglasses inside? Blind people and assholes.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Pretty good. Pretttttty, pretttttttty, prettttttttty good.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("When I was living in New York and didn''t have a penny to my name, I would walk around the streets and occasionally I would see an alcove or something. And I''d think, that''ll be good, that''ll be a good spot for me when I''m homeless.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I''d rather have the thieves than the neighbords - the thieves don''t impose. Thieves just want your things, neighbords want your time. I''d rather give them things than time.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I had a wonderful childhood, which is tough because it''s hard to adjust to a miserable adulthood.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("There''s gotta be a time, there''s gotta be a cutoff point where you can''t have birthday parties. You''re so desperate for a party that you have to have a party two weeks after? Wait till next year, you missed it!", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("When I''m in social situations I always hold onto my glass. It makes me feel comfortable and secure, and I don''t have to shake hands.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Who do you think has more freedom: the married man in America or the single man in Communist China?", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Anybody want to help a semi-retarded individual change a tire?", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Grape works as a soda. Sort of as a gum. I wonder why it doesn''t work as a pie. Grape pie? There''s no grape pie.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I love this dog, it''s not very often you get the chance to be affectionate to something German.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Pretty, pretty, pretty good", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Pretty, pretty, pretty good", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Pretty, pretty, pretty good", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I just wanna close my eyes and go to bed. What else is there to do?", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("I dont like talking to people I know, but strangers I have no problem with.", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Let me tell you something. The Penis doesn''t care about race, creed, or skin color. The penis just wants to get to its homeland! It just wants to go home!", "Larry David");
INSERT INTO lddailies (quote, source) VALUES ("Larrys house has been spray painted by trick-or-treaters he has offended and he''s reporting it to cops] They don''t deserve candy and I don''t deserve this: "Bald Asshole?" That''s a hate crime!", "Larry David");
